# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v_unoauno.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_v_1_a_1(object):
    def setupUi(self, v_1_a_1):
        v_1_a_1.setObjectName("v_1_a_1")
        v_1_a_1.resize(462, 170)
        self.centralwidget = QtWidgets.QWidget(v_1_a_1)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_titulo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titulo.setGeometry(QtCore.QRect(60, 20, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.btn_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_regresar.setGeometry(QtCore.QRect(20, 10, 51, 23))
        self.btn_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_regresar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("importador_musica_videos/img/regreso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_regresar.setIcon(icon)
        self.btn_regresar.setObjectName("btn_regresar")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 90, 311, 70))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_link = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_link.setObjectName("txt_link")
        self.gridLayout.addWidget(self.txt_link, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btn_descargar = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_descargar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_descargar.setObjectName("btn_descargar")
        self.gridLayout.addWidget(self.btn_descargar, 1, 0, 1, 2)
        self.lbl_mensaje = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_mensaje.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mensaje.setObjectName("lbl_mensaje")
        self.gridLayout.addWidget(self.lbl_mensaje, 2, 0, 1, 2)
        v_1_a_1.setCentralWidget(self.centralwidget)

        self.retranslateUi(v_1_a_1)
        QtCore.QMetaObject.connectSlotsByName(v_1_a_1)

    def retranslateUi(self, v_1_a_1):
        _translate = QtCore.QCoreApplication.translate
        v_1_a_1.setWindowTitle(_translate("v_1_a_1", "Descarga 1 por 1"))
        self.lbl_titulo.setText(_translate("v_1_a_1", "<html><head/><body><p align=\"center\">DESCARGADOR DE</p><p align=\"center\">AUDIOS  DE YOUTUBE</p></body></html>"))
        self.label.setText(_translate("v_1_a_1", "Link:"))
        self.btn_descargar.setText(_translate("v_1_a_1", "DESCARGAR"))
        self.lbl_mensaje.setText(_translate("v_1_a_1", "a"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    v_1_a_1 = QtWidgets.QMainWindow()
    ui = Ui_v_1_a_1()
    ui.setupUi(v_1_a_1)
    v_1_a_1.show()
    sys.exit(app.exec_())
