# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v_video_txt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_videos_multiple(object):
    def setupUi(self, videos_multiple):
        videos_multiple.setObjectName("videos_multiple")
        videos_multiple.resize(363, 196)
        self.centralwidget = QtWidgets.QWidget(videos_multiple)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 105, 259, 73))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txt_ruta = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_ruta.setEnabled(False)
        self.txt_ruta.setObjectName("txt_ruta")
        self.gridLayout.addWidget(self.txt_ruta, 1, 0, 1, 1)
        self.btn_ruta = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_ruta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ruta.setObjectName("btn_ruta")
        self.gridLayout.addWidget(self.btn_ruta, 1, 1, 1, 1)
        self.btn_descargar = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_descargar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_descargar.setObjectName("btn_descargar")
        self.gridLayout.addWidget(self.btn_descargar, 2, 0, 1, 2)
        self.btn_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_regresar.setGeometry(QtCore.QRect(20, 30, 31, 23))
        self.btn_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_regresar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("importador_musica_videos/img/regreso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_regresar.setIcon(icon)
        self.btn_regresar.setObjectName("btn_regresar")
        self.lbl_titulo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titulo.setGeometry(QtCore.QRect(60, 40, 261, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        videos_multiple.setCentralWidget(self.centralwidget)

        self.retranslateUi(videos_multiple)
        QtCore.QMetaObject.connectSlotsByName(videos_multiple)

    def retranslateUi(self, videos_multiple):
        _translate = QtCore.QCoreApplication.translate
        videos_multiple.setWindowTitle(_translate("videos_multiple", "Descargador Multiple de Videos"))
        self.label.setText(_translate("videos_multiple", "Ruta del .txt"))
        self.btn_ruta.setText(_translate("videos_multiple", "ELEGIR"))
        self.btn_descargar.setText(_translate("videos_multiple", "DESCARGAR"))
        self.lbl_titulo.setText(_translate("videos_multiple", "<html><head/><body><p align=\"center\">DESCARGADOR DE</p><p align=\"center\">VIDEOS MULTIPLE</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    videos_multiple = QtWidgets.QMainWindow()
    ui = Ui_videos_multiple()
    ui.setupUi(videos_multiple)
    videos_multiple.show()
    sys.exit(app.exec_())
